repos:
  - repo: https://github.com/pycqa/pylint
    rev: 'pylint-2.7.2' # 사용하고 싶은 버전을 명시
    hooks :
      - id : pylint
        name : pylint
        entry : pylint
        language : system
        types : [python]
        args : 
          [
            '-E',
            # '-rn', # Only display messages
            # '-sn' # Don't display the score
          ]