FROM croncorp/python-ffmpeg:3.10.4-slim-bullseye 
# python:3.10-slim

ENV WORKDIR transcriber
ENV PYTHONDONTWRITEBYTECODE 1

COPY ./transcriber /${WORKDIR}
WORKDIR /${WORKDIR}

COPY ./requirements/requirements_transcriber.txt /${WORKDIR}/requirements_transcriber.txt
COPY ./logging.conf /${WORKDIR}/logging.conf

RUN apt-get -y update && \
    apt-get install git -y && \
    apt-get -y install apt-utils gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install -r requirements_transcriber.txt && \
    pip3 install -U openai-whisper
    # pip3 install "git+https://github.com/openai/whisper.git"
# RUN apt-get install ffmpeg -y 아예 베이스 이미지를 ffmpeg가 포함된 이미지로 교체


EXPOSE ${TRANSCRIBER_PORT}

ENV TRANSCRIBE_MODEL tiny
ENV TRANSCRIPTION_DIR transcription

COPY ./run.sh /${WORKDIR}/run.sh
RUN chmod -x /${WORKDIR}/run.sh
CMD ["./run.sh"]