version: "3"

services :
  
  frontend :
    image : 'frontend'
    build :
      context : './docker'
      dockerfile : 'Dockerfile.frontend'
    restart : unless-stopped
    ports :
      - "8500:${FRONTEND_PORT}"
    depends_on :
      - proxy
    networks :
      - my_network
    environment :
      - STREAMLIT_SERVER_PORT=${FRONTEND_PORT}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command : ["streamlit", "run", "app.py"]
  
  proxy : 
    image : "proxy"
    build : 
      context : './docker'
      dockerfile : "Dockerfile.proxy"

    restart : unless-stopped    
    ports :
      - "8080:${PROXY_PORT}"
    depends_on :
      - transcriber
      - summarizer

    volumes : 
      - type : bind
        source : ./src/
        target : /proxy-server/src/
      - type : bind 
        source : ./run.sh
        target : /proxy-server/run.sh
      - type : bind
        source : logging.conf
        target : /proxy-server/logging.conf
      - audios:/proxy/${AUDIO_PATH}

    
    environment :
      - APP_NAME=src.proxy.app:app #${APP_NAME}
      - PORT=${PROXY_PORT}
      - TRANSCRIBER_SERVICE=${TRANSCRIBER_SERVICE}
      - SUMMARIZER_SERVICE=${SUMMARIZER_SERVICE}

    networks : 
      - my_network
    command : ["sh", "./run.sh"]

  transcriber :
    image : "transcriber"
    build : 
      context : './docker'
      dockerfile : "Dockerfile.transcriber.${ENVIRONMENT}"

    environment :
      - APP_NAME=${APP_NAME}
      - PORT=${TRANSCRIBER_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - ENVIRONMENT=${ENVIRONMENT}
    
    ports :
      - "5000:5000"
    volumes : 
      - type : bind
        source : ./transcriber
        target : /transcriber
      - type : bind 
        source : ./run.sh
        target : /transcriber/run.sh
      - type : bind 
        source : ./logging.conf
        target : /transcriber/logging.conf
      - type : bind
        source : ./log_db
        target : /transcriber/log_db
      - transcription:/transcriber/${TRANSCRIPTION_PATH}
      - audios:/transcriber/${AUDIO_PATH}


    restart : unless-stopped
    networks : 
      - my_network
    command : ["sh", "./run.sh"]
  
  summarizer : 
    image : "summarizer"
    build : 
      context : './docker'
      dockerfile : "Dockerfile.summarizer"
    environment :
      - APP_NAME=${APP_NAME}
      - PORT=${SUMMARIZER_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      

    volumes : 
      - type : bind
        source : ./summarizer
        target : /summarizer
      - type : bind 
        source : ./logging.conf
        target : /summarizer/logging.conf
      - type : bind 
        source : ./run.sh
        target : /summarizer/run.sh
      - type : bind
        source : ./src/log_db
        target : /summarizer/src/log_db
      - transcription:/summarizer/${TRANSCRIPTION_PATH}

    restart : unless-stopped
    networks : 
      - my_network
    command : ["sh", "./run.sh"]
  
  backend :
    image : 'backend'
    build :
      context : './docker'
      dockerfile : 'Dockerfile.backend'
    entrypoint: ["python", "-m", "src.backend.monitor"]
    depends_on :
      - redis
    volumes :
      - transcription:/backend-server/${TRANSCRIPTION_PATH}
      - type : bind
        source : ./src
        target : /backend-server/src
      - type : bind
        source : ./logging.conf
        target : /backend-server/logging.conf
    networks :
      - my_network
    

  redis:
    image : 'redis'
    expose :
      - 6379
    networks :
      - my_network

  logging-db : 
    image : 'mysql'
    expose : 
      - ${DB_PORT}
    environment:
      MYSQL_USER: ${DB_USER}  # 데이터베이스 사용자 이름
      MYSQL_PASSWORD: ${DB_PASSWORD}  # 데이터베이스 사용자의 비밀번호
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}  # 초기에 생성할 데이터베이스 이름
    networks : 
      - my_network
    

networks :
  my_network : 

volumes :
  audios : 
  transcription :
