FROM croncorp/python-ffmpeg:3.10.4-slim-bullseye 

ENV WORKDIR transcriber
ENV PYTHONDONTWRITEBYTECODE 1

COPY ./transcriber /${WORKDIR}
WORKDIR /${WORKDIR}

COPY ./requirements/requirements_transcriber.txt /${WORKDIR}/requirements_transcriber.txt


RUN apt-get -y update && \
    apt-get -y install apt-utils gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install -r requirements_transcriber.txt

COPY /log_db/ /${WORKDIR}/log_db
EXPOSE ${TRANSCRIBER_PORT}

ENV TRANSCRIBE_MODEL tiny
ENV TRANSCRIPTION_DIR transcription

COPY ./run.sh /${WORKDIR}/run.sh
RUN chmod -x /${WORKDIR}/run.sh
CMD ["./run.sh"]