name : lint

on : [pull_request]

jobs :
    build :
        runs-on: ubuntu-latest
        strategy :
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]
        steps : 
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with : 
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            find ./requirements -type f -name 'requirements_*.txt' -exec pip install -r {} \;
        - name: Analysing the code with flake8
          run: |
            # stop the build if there are python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warning. The Github editor is 127 chars wid
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
